from config import host_stage
urls_stage = [
    host_stage + "piter-online.net/",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-wifi",
    host_stage + "piter-online.net/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-internet-tv",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-optovolokno",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-1gbit",
    host_stage + "piter-online.net/orders/tohome",
    host_stage + "piter-online.net/rates",
    host_stage + "piter-online.net/rates/domashnij-internet",
    host_stage + "piter-online.net/rates/internet-i-tv",
    host_stage + "piter-online.net/rates/internet-tv-mobile",
    host_stage + "piter-online.net/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rates/internet-100-mbit",
    host_stage + "piter-online.net/rates/internet-300-mbit",
    host_stage + "piter-online.net/rates/internet-500-mbit",
    host_stage + "piter-online.net/rates/1gbit",
    host_stage + "piter-online.net/rates/skorostnoj-internet",
    host_stage + "piter-online.net/rates/gaming",
    host_stage + "piter-online.net/rates/wifi",
    host_stage + "piter-online.net/rates/provodnoj-internet",
    host_stage + "piter-online.net/rates/optovolokno",
    host_stage + "piter-online.net/providers",
    host_stage + "piter-online.net/rating",
    host_stage + "piter-online.net/reviews",
    host_stage + "piter-online.net/address",
    host_stage + "piter-online.net/admiralteiskii-id1192 ",
    host_stage + "piter-online.net/ulicy/internet-provaydery-pr-kt-angliiskii-id267980 ",
    host_stage + "piter-online.net/orders/office",
    host_stage + "piter-online.net/orders/sat",
    host_stage + "piter-online.net/providers/mts",
    host_stage + "piter-online.net/providers/beeline",
    host_stage + "piter-online.net/providers/rostelecom",
    host_stage + "piter-online.net/providers/megafon",
    host_stage + "piter-online.net/providers/tele-2",
    host_stage + "piter-online.net/providers/dom-ru",
    host_stage + "piter-online.net/providers/pakt",
    host_stage + "piter-online.net/providers/mts/rates",
    host_stage + "piter-online.net/providers/mts/rates/internet-i-tv",
    host_stage + "piter-online.net/providers/mts/rates/internet-tv-mobile",
    host_stage + "piter-online.net/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/providers/beeline/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rating/mts",
    host_stage + "piter-online.net/providers/pakt/rates",
    host_stage + "piter-online.net/operatory",
    host_stage + "piter-online.net/operatory/mts",
    host_stage + "piter-online.net/operatory/tele-2",
    host_stage + "piter-online.net/operatory/tinkoff",
    host_stage + "piter-online.net/operatory/megafon",
    host_stage + "piter-online.net/operatory/sbermobile",
    host_stage + "piter-online.net/operatory/yota",
    host_stage + "piter-online.net/operatory/beeline",
    host_stage + "piter-online.net/ratesmobile",
    host_stage + "piter-online.net/nomera",
    host_stage + "piter-online.net/operatory/reviews",
    host_stage + "piter-online.net/ratesmobile/dlja-modema",
    host_stage + "piter-online.net/ratesmobile/dlja-noutbuka",
    host_stage + "piter-online.net/ratesmobile/bezlimitnyj-internet",
    host_stage + "piter-online.net/ratesmobile/vygodnye",
    host_stage + "piter-online.net/ratesmobile/semeinye",
    host_stage + "piter-online.net/ratesmobile/detskie",
    host_stage + "piter-online.net/ratesmobile/mezhdunarodnye",
    host_stage + "piter-online.net/ratesmobile/po-rossii",
    host_stage + "piter-online.net/ratesmobile/esim",
    host_stage + "piter-online.net/ratesmobile/perenos_nomera",
    host_stage + "piter-online.net/operatory/mts/ratesmobile",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/bezlimitnyj-internet",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/vygodnye",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/semeinye",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/detskie",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/po-rossii",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/esim",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/perenos_nomera",
    host_stage + "piter-online.net/operatory/megafon/ratesmobile/dlja-modema",
    host_stage + "piter-online.net/operatory/yota/ratesmobile/dlja-noutbuka",
    host_stage + "piter-online.net/operatory/yota/nomera",
    host_stage + "piter-online.net/operatory/yota/reviews",
    host_stage + "piter-online.net/about/company",
    host_stage + "piter-online.net/about/oplata-i-garantii",
    host_stage + "piter-online.net/articles",
    host_stage + "piter-online.net/experts",
    host_stage + "piter-online.net/articles/luchshaya-simkarta-dlya-interneta",
    host_stage + "piter-online.net/help",
    host_stage + "piter-online.net/help/section-domashnij-internet",
    host_stage + "piter-online.net/help/kak-podklyuchit-domashnij-internet-v-sankt-peterburge",
    host_stage + "piter-online.net/about/contacts",
    host_stage + "piter-online.net/about/partners",
    host_stage + "piter-online.net/site-map",
    host_stage + "piter-online.net/all-regions",
    host_stage + "piter-online.net/all-districts",
    host_stage + "piter-online.net/about/personal-data",
    host_stage + "piter-online.net/about/documents",
    host_stage + "piter-online.net/select-region",
]

urls_prod = [
    "https://piter-online.net/",
    "https://piter-online.net/domashniy-internet/podklyuchit-deshevyj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-wifi",
    "https://piter-online.net/domashniy-internet/besplatnoe-podklyuchenie",
    "https://piter-online.net/domashniy-internet/podklyuchit-skorostnoj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-internet-tv",
    "https://piter-online.net/domashniy-internet/podklyuchit-optovolokno",
    "https://piter-online.net/domashniy-internet/podklyuchit-provodnoj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-1gbit",
    "https://piter-online.net/orders/tohome",
    "https://piter-online.net/rates",
    "https://piter-online.net/rates/domashnij-internet",
    "https://piter-online.net/rates/internet-i-tv",
    "https://piter-online.net/rates/internet-tv-mobile",
    "https://piter-online.net/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rates/internet-100-mbit",
    "https://piter-online.net/rates/internet-300-mbit",
    "https://piter-online.net/rates/internet-500-mbit",
    "https://piter-online.net/rates/1gbit",
    "https://piter-online.net/rates/skorostnoj-internet",
    "https://piter-online.net/rates/gaming",
    "https://piter-online.net/rates/wifi",
    "https://piter-online.net/rates/provodnoj-internet",
    "https://piter-online.net/rates/optovolokno",
    "https://piter-online.net/providers",
    "https://piter-online.net/rating",
    "https://piter-online.net/reviews",
    "https://piter-online.net/address",
    "https://piter-online.net/admiralteiskii-id1192 ",
    "https://piter-online.net/ulicy/internet-provaydery-pr-kt-angliiskii-id267980 ",
    "https://piter-online.net/orders/office",
    "https://piter-online.net/orders/sat",
    "https://piter-online.net/providers/mts",
    "https://piter-online.net/providers/beeline",
    "https://piter-online.net/providers/rostelecom",
    "https://piter-online.net/providers/megafon",
    "https://piter-online.net/providers/tele-2",
    "https://piter-online.net/providers/dom-ru",
    "https://piter-online.net/providers/pakt",
    "https://piter-online.net/providers/mts/rates",
    "https://piter-online.net/providers/mts/rates/internet-i-tv",
    "https://piter-online.net/providers/mts/rates/internet-tv-mobile",
    "https://piter-online.net/providers/mts/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/beeline/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rating/mts",
    "https://piter-online.net/providers/pakt/rates",
    "https://piter-online.net/operatory",
    "https://piter-online.net/operatory/mts",
    "https://piter-online.net/operatory/tele-2",
    "https://piter-online.net/operatory/tinkoff",
    "https://piter-online.net/operatory/megafon",
    "https://piter-online.net/operatory/sbermobile",
    "https://piter-online.net/operatory/yota",
    "https://piter-online.net/operatory/beeline",
    "https://piter-online.net/ratesmobile",
    "https://piter-online.net/nomera",
    "https://piter-online.net/operatory/reviews",
    "https://piter-online.net/ratesmobile/dlja-modema",
    "https://piter-online.net/ratesmobile/dlja-noutbuka",
    "https://piter-online.net/ratesmobile/bezlimitnyj-internet",
    "https://piter-online.net/ratesmobile/vygodnye",
    "https://piter-online.net/ratesmobile/semeinye",
    "https://piter-online.net/ratesmobile/detskie",
    "https://piter-online.net/ratesmobile/mezhdunarodnye",
    "https://piter-online.net/ratesmobile/po-rossii",
    "https://piter-online.net/ratesmobile/esim",
    "https://piter-online.net/ratesmobile/perenos_nomera",
    "https://piter-online.net/operatory/mts/ratesmobile",
    "https://piter-online.net/operatory/mts/ratesmobile/bezlimitnyj-internet",
    "https://piter-online.net/operatory/mts/ratesmobile/vygodnye",
    "https://piter-online.net/operatory/mts/ratesmobile/semeinye",
    "https://piter-online.net/operatory/mts/ratesmobile/detskie",
    "https://piter-online.net/operatory/mts/ratesmobile/po-rossii",
    "https://piter-online.net/operatory/mts/ratesmobile/esim",
    "https://piter-online.net/operatory/mts/ratesmobile/perenos_nomera",
    "https://piter-online.net/operatory/megafon/ratesmobile/dlja-modema",
    "https://piter-online.net/operatory/yota/ratesmobile/dlja-noutbuka",
    "https://piter-online.net/operatory/yota/nomera",
    "https://piter-online.net/operatory/yota/reviews",
    "https://piter-online.net/about/company",
    "https://piter-online.net/about/oplata-i-garantii",
    "https://piter-online.net/articles",
    "https://piter-online.net/experts",
    "https://piter-online.net/articles/luchshaya-simkarta-dlya-interneta",
    "https://piter-online.net/help",
    "https://piter-online.net/help/section-domashnij-internet",
    "https://piter-online.net/help/kak-podklyuchit-domashnij-internet-v-sankt-peterburge",
    "https://piter-online.net/about/contacts",
    "https://piter-online.net/about/partners",
    "https://piter-online.net/site-map",
    "https://piter-online.net/all-regions",
    "https://piter-online.net/all-districts",
    "https://piter-online.net/about/personal-data",
    "https://piter-online.net/about/documents",
    "https://piter-online.net/select-region"
]