from config import host_stage_second
urls_stage = [
    host_stage_second + "101internet.ru/",
    host_stage_second + "101internet.ru/orders/tohome",
    host_stage_second + "101internet.ru/rates",
    host_stage_second + "101internet.ru/providers",
    host_stage_second + "101internet.ru/ekaterinburg",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-wifi",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-internet-tv",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-optovolokno",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-1gbit",
    host_stage_second + "101internet.ru/ekaterinburg/orders/tohome",
    host_stage_second + "101internet.ru/ekaterinburg/rates",
    host_stage_second + "101internet.ru/ekaterinburg/rates/domashnij-internet",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-i-tv",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-tv-mobile",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-i-mobilnaya-svyaz",
    host_stage_second + "101internet.ru/ekaterinburg/rates/nedorogoj-domashnij-internet",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-100-mbit",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-300-mbit",
    host_stage_second + "101internet.ru/ekaterinburg/rates/internet-500-mbit",
    host_stage_second + "101internet.ru/ekaterinburg/rates/1gbit",
    host_stage_second + "101internet.ru/ekaterinburg/rates/skorostnoj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/rates/gaming",
    host_stage_second + "101internet.ru/ekaterinburg/rates/wifi",
    host_stage_second + "101internet.ru/ekaterinburg/rates/provodnoj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/rates/optovolokno",
    host_stage_second + "101internet.ru/ekaterinburg/providers",
    host_stage_second + "101internet.ru/ekaterinburg/rating",
    host_stage_second + "101internet.ru/ekaterinburg/reviews",
    host_stage_second + "101internet.ru/ekaterinburg/address",
    host_stage_second + "101internet.ru/ekaterinburg/address/%D0%B2%D0%B5%D1%80%D1%85-%D0%B8%D1%81%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9-id1304",
    host_stage_second + "101internet.ru/ekaterinburg/address/%D0%B2%D0%B5%D1%80%D1%85-%D0%B8%D1%81%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9-id1304/%D1%83%D0%BB-%D0%B1%D0%B5%D0%BB%D0%BE%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F-id296498",
    host_stage_second + "101internet.ru/ekaterinburg/orders/office",
    host_stage_second + "101internet.ru/ekaterinburg/orders/sat",
    host_stage_second + "101internet.ru/ekaterinburg/providers/mts",
    host_stage_second + "101internet.ru/ekaterinburg/providers/beeline",
    host_stage_second + "101internet.ru/ekaterinburg/providers/rostelecom",
    host_stage_second + "101internet.ru/ekaterinburg/providers/megafon",
    host_stage_second + "101internet.ru/ekaterinburg/providers/tele-2",
    host_stage_second + "101internet.ru/ekaterinburg/providers/dom-ru",
    host_stage_second + "101internet.ru/ekaterinburg/providers/ttk",
    host_stage_second + "101internet.ru/ekaterinburg/providers/mts/rates",
    host_stage_second + "101internet.ru/ekaterinburg/providers/mts/rates/internet-i-tv",
    host_stage_second + "101internet.ru/ekaterinburg/providers/mts/rates/internet-tv-mobile",
    host_stage_second + "101internet.ru/ekaterinburg/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage_second + "101internet.ru/ekaterinburg/providers/beeline/rates/nedorogoj-domashnij-internet",
    host_stage_second + "101internet.ru/ekaterinburg/rating/mts",
    host_stage_second + "101internet.ru/ekaterinburg/providers/ttk/rates",
    host_stage_second + "101internet.ru/ekaterinburg/operatory",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/tele-2",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/tinkoff",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/megafon",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/sbermobile",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/yota",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/beeline",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile",
    host_stage_second + "101internet.ru/ekaterinburg/nomera",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/reviews",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/dlja-modema",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/dlja-noutbuka",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/bezlimitnyj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/vygodnye",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/semeinye",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/detskie",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/mezhdunarodnye",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/po-rossii",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/esim",
    host_stage_second + "101internet.ru/ekaterinburg/ratesmobile/perenos_nomera",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/bezlimitnyj-internet",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/vygodnye",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/semeinye",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/detskie",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/po-rossii",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/esim",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/mts/ratesmobile/perenos_nomera",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/dlja-modema",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/yota/ratesmobile/dlja-noutbuka",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/yota/nomera",
    host_stage_second + "101internet.ru/ekaterinburg/operatory/yota/reviews",
    host_stage_second + "101internet.ru/about/company",
    host_stage_second + "101internet.ru/about/oplata-i-garantii",
    host_stage_second + "101internet.ru/articles",
    host_stage_second + "101internet.ru/experts",
    host_stage_second + "101internet.ru/articles/luchshie-tarify-dlya-simkart",
    host_stage_second + "101internet.ru/help",
    host_stage_second + "101internet.ru/help/section-domashnij-internet",
    host_stage_second + "101internet.ru/help/kak-vybrat-podhodyashchij-internet-tarif",
    host_stage_second + "101internet.ru/about/contacts",
    host_stage_second + "101internet.ru/about/partners",
    host_stage_second + "101internet.ru/ekaterinburg/site-map",
    host_stage_second + "101internet.ru/all-regions",
    host_stage_second + "101internet.ru/ekaterinburg/all-districts",
    host_stage_second + "101internet.ru/about/personal-data",
    host_stage_second + "101internet.ru/about/documents",
    host_stage_second + "101internet.ru/select-region"
    ]

main_urls_prod = [
    "https://101internet.ru/",
    "https://101internet.ru/orders/tohome",
    "https://101internet.ru/rates",
    "https://101internet.ru/providers",
    "https://101internet.ru/ekaterinburg",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-deshevyj-internet",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-wifi",
    "https://101internet.ru/ekaterinburg/domashniy-internet/besplatnoe-podklyuchenie",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-skorostnoj-internet",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-internet-tv",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-optovolokno",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-provodnoj-internet",
    "https://101internet.ru/ekaterinburg/domashniy-internet/podklyuchit-1gbit",
    "https://101internet.ru/ekaterinburg/orders/tohome",
    "https://101internet.ru/ekaterinburg/rates",
    "https://101internet.ru/ekaterinburg/rates/domashnij-internet",
    "https://101internet.ru/ekaterinburg/rates/internet-i-tv",
    "https://101internet.ru/ekaterinburg/rates/internet-tv-mobile",
    "https://101internet.ru/ekaterinburg/rates/internet-i-mobilnaya-svyaz",
    "https://101internet.ru/ekaterinburg/rates/nedorogoj-domashnij-internet",
    "https://101internet.ru/ekaterinburg/rates/internet-100-mbit",
    "https://101internet.ru/ekaterinburg/rates/internet-300-mbit",
    "https://101internet.ru/ekaterinburg/rates/internet-500-mbit",
    "https://101internet.ru/ekaterinburg/rates/1gbit",
    "https://101internet.ru/ekaterinburg/rates/skorostnoj-internet",
    "https://101internet.ru/ekaterinburg/rates/gaming",
    "https://101internet.ru/ekaterinburg/rates/wifi",
    "https://101internet.ru/ekaterinburg/rates/provodnoj-internet",
    "https://101internet.ru/ekaterinburg/rates/optovolokno",
    "https://101internet.ru/ekaterinburg/providers",
    "https://101internet.ru/ekaterinburg/rating",
    "https://101internet.ru/ekaterinburg/reviews",
    "https://101internet.ru/ekaterinburg/address",
    "https://101internet.ru/ekaterinburg/address/%D0%B2%D0%B5%D1%80%D1%85-%D0%B8%D1%81%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9-id1304",
    "https://101internet.ru/ekaterinburg/address/%D0%B2%D0%B5%D1%80%D1%85-%D0%B8%D1%81%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9-id1304/%D1%83%D0%BB-%D0%B1%D0%B5%D0%BB%D0%BE%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F-id296498",
    "https://101internet.ru/ekaterinburg/orders/office",
    "https://101internet.ru/ekaterinburg/orders/sat",
    "https://101internet.ru/ekaterinburg/providers/mts",
    "https://101internet.ru/ekaterinburg/providers/beeline",
    "https://101internet.ru/ekaterinburg/providers/rostelecom",
    "https://101internet.ru/ekaterinburg/providers/megafon",
    "https://101internet.ru/ekaterinburg/providers/tele-2",
    "https://101internet.ru/ekaterinburg/providers/dom-ru",
    "https://101internet.ru/ekaterinburg/providers/ttk",
    "https://101internet.ru/ekaterinburg/providers/mts/rates",
    "https://101internet.ru/ekaterinburg/providers/mts/rates/internet-i-tv",
    "https://101internet.ru/ekaterinburg/providers/mts/rates/internet-tv-mobile",
    "https://101internet.ru/ekaterinburg/providers/mts/rates/internet-i-mobilnaya-svyaz",
    "https://101internet.ru/ekaterinburg/providers/beeline/rates/nedorogoj-domashnij-internet",
    "https://101internet.ru/ekaterinburg/rating/mts",
    "https://101internet.ru/ekaterinburg/providers/ttk/rates",
    "https://101internet.ru/ekaterinburg/operatory",
    "https://101internet.ru/ekaterinburg/operatory/mts",
    "https://101internet.ru/ekaterinburg/operatory/tele-2",
    "https://101internet.ru/ekaterinburg/operatory/tinkoff",
    "https://101internet.ru/ekaterinburg/operatory/megafon",
    "https://101internet.ru/ekaterinburg/operatory/sbermobile",
    "https://101internet.ru/ekaterinburg/operatory/yota",
    "https://101internet.ru/ekaterinburg/operatory/beeline",
    "https://101internet.ru/ekaterinburg/ratesmobile",
    "https://101internet.ru/ekaterinburg/nomera",
    "https://101internet.ru/ekaterinburg/operatory/reviews",
    "https://101internet.ru/ekaterinburg/ratesmobile/dlja-modema",
    "https://101internet.ru/ekaterinburg/ratesmobile/dlja-noutbuka",
    "https://101internet.ru/ekaterinburg/ratesmobile/bezlimitnyj-internet",
    "https://101internet.ru/ekaterinburg/ratesmobile/vygodnye",
    "https://101internet.ru/ekaterinburg/ratesmobile/semeinye",
    "https://101internet.ru/ekaterinburg/ratesmobile/detskie",
    "https://101internet.ru/ekaterinburg/ratesmobile/mezhdunarodnye",
    "https://101internet.ru/ekaterinburg/ratesmobile/po-rossii",
    "https://101internet.ru/ekaterinburg/ratesmobile/esim",
    "https://101internet.ru/ekaterinburg/ratesmobile/perenos_nomera",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/bezlimitnyj-internet",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/vygodnye",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/semeinye",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/detskie",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/po-rossii",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/esim",
    "https://101internet.ru/ekaterinburg/operatory/mts/ratesmobile/perenos_nomera",
    "https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/dlja-modema",
    "https://101internet.ru/ekaterinburg/operatory/yota/ratesmobile/dlja-noutbuka",
    "https://101internet.ru/ekaterinburg/operatory/yota/nomera",
    "https://101internet.ru/ekaterinburg/operatory/yota/reviews",
    "https://101internet.ru/about/company",
    "https://101internet.ru/about/oplata-i-garantii",
    "https://101internet.ru/articles",
    "https://101internet.ru/experts",
    "https://101internet.ru/articles/luchshie-tarify-dlya-simkart",
    "https://101internet.ru/help",
    "https://101internet.ru/help/section-domashnij-internet",
    "https://101internet.ru/help/kak-vybrat-podhodyashchij-internet-tarif",
    "https://101internet.ru/about/contacts",
    "https://101internet.ru/about/partners",
    "https://101internet.ru/ekaterinburg/site-map",
    "https://101internet.ru/all-regions",
    "https://101internet.ru/ekaterinburg/all-districts",
    "https://101internet.ru/about/personal-data",
    "https://101internet.ru/about/documents",
    "https://101internet.ru/select-region"
]