from config import host_stage
urls_stage = [
    host_stage + "moskvaonline.ru/",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-wifi",
    host_stage + "moskvaonline.ru/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-internet-tv",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-optovolokno",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-1gbit",
    host_stage + "moskvaonline.ru/orders/tohome",
    host_stage + "moskvaonline.ru/rates",
    host_stage + "moskvaonline.ru/rates/domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-100-mbit",
    host_stage + "moskvaonline.ru/rates/internet-300-mbit",
    host_stage + "moskvaonline.ru/rates/internet-500-mbit",
    host_stage + "moskvaonline.ru/rates/1gbit",
    host_stage + "moskvaonline.ru/rates/skorostnoj-internet",
    host_stage + "moskvaonline.ru/rates/gaming",
    host_stage + "moskvaonline.ru/rates/wifi",
    host_stage + "moskvaonline.ru/rates/provodnoj-internet",
    host_stage + "moskvaonline.ru/rates/optovolokno",
    host_stage + "moskvaonline.ru/providers",
    host_stage + "moskvaonline.ru/rating",
    host_stage + "moskvaonline.ru/reviews",
    host_stage + "moskvaonline.ru/address",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D0%BF%D1%80-%D0%BA%D1%82-60-%D0%BB%D0%B5%D1%82%D0%B8%D1%8F-%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8F-id294128",
    host_stage + "moskvaonline.ru/orders/office",
    host_stage + "moskvaonline.ru/orders/sat",
    host_stage + "moskvaonline.ru/providers/mts",
    host_stage + "moskvaonline.ru/providers/beeline",
    host_stage + "moskvaonline.ru/providers/rostelecom",
    host_stage + "moskvaonline.ru/providers/megafon",
    host_stage + "moskvaonline.ru/providers/tele-2",
    host_stage + "moskvaonline.ru/providers/dom-ru",
    host_stage + "moskvaonline.ru/providers/akado",
    host_stage + "moskvaonline.ru/providers/mts/rates",
    host_stage + "moskvaonline.ru/providers/mts/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/providers/mts/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/providers/beeline/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rating/mts",
    host_stage + "moskvaonline.ru/providers/akado/rates",
    host_stage + "moskvaonline.ru/operatory",
    host_stage + "moskvaonline.ru/operatory/mts",
    host_stage + "moskvaonline.ru/operatory/tele-2",
    host_stage + "moskvaonline.ru/operatory/tinkoff",
    host_stage + "moskvaonline.ru/operatory/megafon",
    host_stage + "moskvaonline.ru/operatory/sbermobile",
    host_stage + "moskvaonline.ru/operatory/yota",
    host_stage + "moskvaonline.ru/operatory/beeline",
    host_stage + "moskvaonline.ru/ratesmobile",
    host_stage + "moskvaonline.ru/nomera",
    host_stage + "moskvaonline.ru/operatory/reviews",
    host_stage + "moskvaonline.ru/ratesmobile/dlja-modema",
    host_stage + "moskvaonline.ru/ratesmobile/dlja-noutbuka",
    host_stage + "moskvaonline.ru/ratesmobile/bezlimitnyj-internet",
    host_stage + "moskvaonline.ru/ratesmobile/vygodnye",
    host_stage + "moskvaonline.ru/ratesmobile/semeinye",
    host_stage + "moskvaonline.ru/ratesmobile/detskie",
    host_stage + "moskvaonline.ru/ratesmobile/mezhdunarodnye",
    host_stage + "moskvaonline.ru/ratesmobile/po-rossii",
    host_stage + "moskvaonline.ru/ratesmobile/esim",
    host_stage + "moskvaonline.ru/ratesmobile/perenos_nomera",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/bezlimitnyj-internet",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/vygodnye",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/semeinye",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/detskie",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/po-rossii",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/esim",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile/perenos_nomera",
    host_stage + "moskvaonline.ru/operatory/megafon/ratesmobile/dlja-modema",
    host_stage + "moskvaonline.ru/operatory/yota/ratesmobile/dlja-noutbuka",
    host_stage + "moskvaonline.ru/operatory/yota/nomera",
    host_stage + "moskvaonline.ru/operatory/yota/reviews",
    host_stage + "moskvaonline.ru/about/company",
    host_stage + "moskvaonline.ru/about/oplata-i-garantii",
    host_stage + "moskvaonline.ru/articles",
    host_stage + "moskvaonline.ru/experts",
    host_stage + "moskvaonline.ru/articles/lampochki-na-routere-chto-oznachayut",
    host_stage + "moskvaonline.ru/help",
    host_stage + "moskvaonline.ru/help/section-first",
    host_stage + "moskvaonline.ru/help/kak-podklyuchit-internet-v-novostrojke ",
    host_stage + "moskvaonline.ru/about/contacts",
    host_stage + "moskvaonline.ru/about/partners",
    host_stage + "moskvaonline.ru/site-map",
    host_stage + "moskvaonline.ru/all-regions",
    host_stage + "moskvaonline.ru/all-districts",
    host_stage + "moskvaonline.ru/about/personal-data",
    host_stage + "moskvaonline.ru/about/documents",
    host_stage + "moskvaonline.ru/select-region",
]

mol_urls_prod = [
    "https://www.moskvaonline.ru/",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-deshevyj-internet",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-wifi",
    "https://www.moskvaonline.ru/domashniy-internet/besplatnoe-podklyuchenie",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-skorostnoj-internet",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-internet-tv",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-optovolokno",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-provodnoj-internet",
    "https://www.moskvaonline.ru/domashniy-internet/podklyuchit-1gbit",
    "https://www.moskvaonline.ru/orders/tohome",
    "https://www.moskvaonline.ru/rates",
    "https://www.moskvaonline.ru/rates/domashnij-internet",
    "https://www.moskvaonline.ru/rates/internet-i-tv",
    "https://www.moskvaonline.ru/rates/internet-tv-mobile",
    "https://www.moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    "https://www.moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    "https://www.moskvaonline.ru/rates/internet-100-mbit",
    "https://www.moskvaonline.ru/rates/internet-300-mbit",
    "https://www.moskvaonline.ru/rates/internet-500-mbit",
    "https://www.moskvaonline.ru/rates/1gbit",
    "https://www.moskvaonline.ru/rates/skorostnoj-internet",
    "https://www.moskvaonline.ru/rates/gaming",
    "https://www.moskvaonline.ru/rates/wifi",
    "https://www.moskvaonline.ru/rates/provodnoj-internet",
    "https://www.moskvaonline.ru/rates/optovolokno",
    "https://www.moskvaonline.ru/providers",
    "https://www.moskvaonline.ru/rating",
    "https://www.moskvaonline.ru/reviews",
    "https://www.moskvaonline.ru/address",
    "https://www.moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    "https://www.moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D0%BF%D1%80-%D0%BA%D1%82-60-%D0%BB%D0%B5%D1%82%D0%B8%D1%8F-%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8F-id294128",
    "https://www.moskvaonline.ru/orders/office",
    "https://www.moskvaonline.ru/orders/sat",
    "https://www.moskvaonline.ru/providers/mts",
    "https://www.moskvaonline.ru/providers/beeline",
    "https://www.moskvaonline.ru/providers/rostelecom",
    "https://www.moskvaonline.ru/providers/megafon",
    "https://www.moskvaonline.ru/providers/tele-2",
    "https://www.moskvaonline.ru/providers/dom-ru",
    "https://www.moskvaonline.ru/providers/akado",
    "https://www.moskvaonline.ru/providers/mts/rates",
    "https://www.moskvaonline.ru/providers/mts/rates/internet-i-tv",
    "https://www.moskvaonline.ru/providers/mts/rates/internet-tv-mobile",
    "https://www.moskvaonline.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    "https://www.moskvaonline.ru/providers/beeline/rates/nedorogoj-domashnij-internet",
    "https://www.moskvaonline.ru/rating/mts",
    "https://www.moskvaonline.ru/providers/akado/rates",
    "https://www.moskvaonline.ru/operatory",
    "https://www.moskvaonline.ru/operatory/mts",
    "https://www.moskvaonline.ru/operatory/tele-2",
    "https://www.moskvaonline.ru/operatory/tinkoff",
    "https://www.moskvaonline.ru/operatory/megafon",
    "https://www.moskvaonline.ru/operatory/sbermobile",
    "https://www.moskvaonline.ru/operatory/yota",
    "https://www.moskvaonline.ru/operatory/beeline",
    "https://www.moskvaonline.ru/ratesmobile",
    "https://www.moskvaonline.ru/nomera",
    "https://www.moskvaonline.ru/operatory/reviews",
    "https://www.moskvaonline.ru/ratesmobile/dlja-modema",
    "https://www.moskvaonline.ru/ratesmobile/dlja-noutbuka",
    "https://www.moskvaonline.ru/ratesmobile/bezlimitnyj-internet",
    "https://www.moskvaonline.ru/ratesmobile/vygodnye",
    "https://www.moskvaonline.ru/ratesmobile/semeinye",
    "https://www.moskvaonline.ru/ratesmobile/detskie",
    "https://www.moskvaonline.ru/ratesmobile/mezhdunarodnye",
    "https://www.moskvaonline.ru/ratesmobile/po-rossii",
    "https://www.moskvaonline.ru/ratesmobile/esim",
    "https://www.moskvaonline.ru/ratesmobile/perenos_nomera",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/bezlimitnyj-internet",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/vygodnye",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/semeinye",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/detskie",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/po-rossii",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/esim",
    "https://www.moskvaonline.ru/operatory/mts/ratesmobile/perenos_nomera",
    "https://www.moskvaonline.ru/operatory/megafon/ratesmobile/dlja-modema",
    "https://www.moskvaonline.ru/operatory/yota/ratesmobile/dlja-noutbuka",
    "https://www.moskvaonline.ru/operatory/yota/nomera",
    "https://www.moskvaonline.ru/operatory/yota/reviews",
    "https://www.moskvaonline.ru/about/company",
    "https://www.moskvaonline.ru/about/oplata-i-garantii",
    "https://www.moskvaonline.ru/articles",
    "https://www.moskvaonline.ru/experts",
    "https://www.moskvaonline.ru/articles/lampochki-na-routere-chto-oznachayut",
    "https://www.moskvaonline.ru/help",
    "https://www.moskvaonline.ru/help/section-first",
    "https://www.moskvaonline.ru/help/kak-podklyuchit-internet-v-novostrojke ",
    "https://www.moskvaonline.ru/about/contacts",
    "https://www.moskvaonline.ru/about/partners",
    "https://www.moskvaonline.ru/site-map",
    "https://www.moskvaonline.ru/all-regions",
    "https://www.moskvaonline.ru/all-districts",
    "https://www.moskvaonline.ru/about/personal-data",
    "https://www.moskvaonline.ru/about/documents",
    "https://www.moskvaonline.ru/select-region"

]